Repository AY2021S1-CS2103-F09-4/tp, pull requests merged in 2020-10, with the labels that each got.

#25 Update README and User Guide
  README.md
  docs/UserGuide.md
  docs/index.md
Labels: type.Website

#34 Create Use cases
  docs/DeveloperGuide.md
Labels: type.Website

#41 Refactor Person to Client and add Client Command
  LICENSE
  docs/DeveloperGuide.md
  docs/tutorials/AddRemark.md
  docs/tutorials/RemovingFields.md
  docs/tutorials/TracingCode.md
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/ClientCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ClientCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/person/Client.java
  src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedClient.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditClientDescriptorTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/person/ClientTest.java
  src/test/java/seedu/address/model/person/UniqueClientListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedClientTest.java
  src/test/java/seedu/address/storage/JsonAddressBookStorageTest.java
  src/test/java/seedu/address/testutil/AddressBookBuilder.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TestUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High

#48 create order command
  docs/UserGuide.md
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/OrderCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/OrderCommandParser.java
  src/main/java/seedu/address/model/person/Client.java
  src/main/java/seedu/address/model/person/Order.java
Labels: priority.High, type.Story

#65 Add functionality for searching for orders by their descriptions
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/FindOrderCommand.java
  src/main/java/seedu/address/logic/commands/OrderCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/FindOrderCommandParser.java
  src/main/java/seedu/address/model/person/DescriptionContainsKeywordsPredicate.java
Labels: priority.High, type.Story

#64 Update the UI to show more information
  src/main/java/seedu/address/ui/ErrorWindow.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/OrderCard.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/ErrorWindow.fxml
  src/main/resources/view/LightTheme.css
  src/main/resources/view/NewMainWindow.fxml
  src/main/resources/view/OrderListCard.fxml
Labels: priority.High

#67 Update DG to include details on the 'find' and 'findorder' commands
  build.gradle
  docs/DeveloperGuide.md
  src/main/java/seedu/address/logic/commands/FindOrderCommand.java
  src/main/java/seedu/address/logic/parser/FindOrderCommandParser.java
  src/main/java/seedu/address/model/person/DescriptionContainsKeywordsPredicate.java
Labels: type.Documentation

#66 List Client and Orders Command
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/ListOrderCommand.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/UiManager.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
Labels: type.Enhancement, type.Story

#71 Deleting Orders upon Deleting Clients
  docs/DeveloperGuide.md
  src/main/java/seedu/address/logic/commands/DeleteOrderCommand.java
  src/main/java/seedu/address/logic/commands/DoneCommand.java
  src/main/java/seedu/address/logic/parser/DeleteOrderCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/person/Order.java
  src/test/java/seedu/address/logic/commands/DeleteClientCommandTest.java
  src/test/java/seedu/address/storage/JsonAddressBookStorageTest.java
Labels: type.Enhancement

#72 Update DeveloperGuide.md to include list command
  docs/DeveloperGuide.md
Labels: type.Documentation

#79 Fix Delete Client Indexing
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/person/Order.java
  src/main/java/seedu/address/model/person/OrderIdContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteClientCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteOrderCommandTest.java
  src/test/java/seedu/address/testutil/OrderBuilder.java
  src/test/java/seedu/address/testutil/TypicalOrders.java
Labels: severity.Medium, type.Bug

#85 Update User Guide for Delete Commands
  docs/UserGuide.md
  docs/images/InvalidDeleteClientCommand.png
  docs/images/InvalidDeleteOrderCommand.png
  docs/images/LogOnceHeader.png
  docs/images/ValidDeleteClientCommand.png
  docs/images/ValidDeleteOrderCommand.png
Labels: type.Website

#86 Enhance search function with tokens for more specificity
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/FindOrderCommand.java
  src/main/java/seedu/address/logic/commands/OrderCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/FindOrderCommandParser.java
  src/main/java/seedu/address/model/person/ClientAddressPredicate.java
  src/main/java/seedu/address/model/person/ClientEmailPredicate.java
  src/main/java/seedu/address/model/person/ClientMultiPredicate.java
  src/main/java/seedu/address/model/person/ClientPhonePredicate.java
  src/main/java/seedu/address/model/person/OrderAddressPredicate.java
  src/main/java/seedu/address/model/person/OrderClientIdPredicate.java
  src/main/java/seedu/address/model/person/OrderDatePredicate.java
  src/main/java/seedu/address/model/person/OrderMultiPredicate.java
  src/main/java/seedu/address/storage/JsonAdaptedOrder.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
Labels: type.Enhancement

#94 Update user guide to include commands for finding clients and orders
  docs/UserGuide.md
Labels: priority.High, type.Documentation
