Repository AY2021S1-CS2103-F09-4/tp, pull requests merged in 2020-11, with the labels that each got.

#156 Update Order Creation Conditions
  src/main/java/seedu/address/logic/commands/OrderCommand.java
  src/main/java/seedu/address/logic/parser/OrderCommandParser.java
Labels: type.Bug

#159 Integrate Update order and add UI elements for all CRUD operations
  build.gradle
  src/main/java/seedu/address/logic/commands/DeleteClientCommand.java
  src/main/java/seedu/address/logic/commands/DeleteOrderCommand.java
  src/main/java/seedu/address/logic/commands/DoneCommand.java
  src/main/java/seedu/address/logic/commands/UpdateClientCommand.java
  src/main/java/seedu/address/logic/commands/UpdateOrderCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Order.java
  src/main/java/seedu/address/model/person/OrderClientIdPredicate.java
  src/main/java/seedu/address/storage/JsonAdaptedOrder.java
  src/main/java/seedu/address/ui/ClientInfoDisplay.java
  src/main/java/seedu/address/ui/EditClientForm.java
  src/main/java/seedu/address/ui/EditOrderForm.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/OrderInfoDisplay.java
  src/main/java/seedu/address/ui/events/EditClientEvent.java
  src/main/java/seedu/address/ui/events/EditEvent.java
  src/main/java/seedu/address/ui/events/EditOrderEvent.java
  src/main/java/seedu/address/ui/events/LogOnceEventHandler.java
  src/main/java/seedu/address/ui/events/OrderCompleteEvent.java
  src/main/resources/view/ClientInfoDisplay.fxml
  src/main/resources/view/EditClientForm.fxml
  src/main/resources/view/EditOrderForm.fxml
  src/main/resources/view/NewMainWindow.fxml
  src/main/resources/view/OrderInfoDisplay.fxml
  src/test/java/seedu/address/logic/commands/DeleteClientCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteOrderCommandTest.java
Labels: priority.High

#162 Fix Bugs
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/DeleteClientCommand.java
  src/main/java/seedu/address/logic/commands/DeleteOrderCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteOrderCommandParser.java
  src/main/java/seedu/address/logic/parser/UpdateClientCommandParser.java
  src/main/java/seedu/address/logic/parser/UpdateOrderCommandParser.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/resources/view/ClientInfoDisplay.fxml
  src/main/resources/view/NewMainWindow.fxml
  src/main/resources/view/OrderInfoDisplay.fxml
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ClientCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: type.Bug

#161 Update documentation and some bug fixes
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/DoneCommand.java
  src/main/java/seedu/address/ui/OrderCard.java
  src/main/resources/view/OrderListCard.fxml
Labels: type.Documentation

#173 Add test code for DoneCommand
  src/main/java/seedu/address/logic/commands/DoneCommand.java
  src/test/java/seedu/address/logic/commands/DoneCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
Labels: priority.High, type.Chore
